config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about', to: 'about#index', as: 'about'
  get 'home', to: 'home#index', as: 'home'

  resources :episodes, only: %i[index show]
  resources :characters, only: %i[index show] do
    collection do
      get 'search_results'
    end
  end

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  has_one :favourite_food
  has_many :character_episodes
  has_many :episodes, through: :character_episodes

  validates :name, :image, presence: true
end

app/models/character_episode.rb
class CharacterEpisode < ApplicationRecord
  belongs_to :character
  belongs_to :episode
end

app/models/characterepisode.rb
# frozen_string_literal: true

class Characterepisode < ApplicationRecord
  belongs_to :character
  belongs_to :episode

  validates :character, :episode, presence: true
end

app/models/episode.rb
# frozen_string_literal: true

class Episode < ApplicationRecord
  has_many :character_episodes
  has_many :characters, through: :character_episodes

  validates :name, :episode_name, presence: true
end

app/models/favourite_food.rb
class FavouriteFood < ApplicationRecord
  belongs_to :character

  validates :name, :description, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
# frozen_string_literal: true

class CharactersController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @characters = pagy(Character.order(:id))
  end

  def show
    @character = Character.find(params[:id])
  end

  def search_results
    @query = params[:query]
    @pagy, @characters = pagy(Character.where('name LIKE ?', "%#{@query}%"))
  end
end

app/controllers/episodes_controller.rb
# frozen_string_literal: true

class EpisodesController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @episodes = pagy(Episode.order(:id))
  end

  def show
    @episode = Episode.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>About the Rick and Morty website</h1>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/characters">Characters</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/episodes">Episodes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
  </ul>

  <%= form_with(url: search_results_characters_path, method: "get", class:"form-inline", local: true) do %>
    <%= text_field_tag(:query, "", class:"form-control mr-sm-2",placeholder:"Search Characters") %>
    <%= submit_tag("Search", class:"btn btn-success") %>
  <% end %>
</nav>

<p>I will be grabbing my main data from a Rick and Morty API and I
will be adding bogus data from the Faker gem. There is a dataset of
all the characters, the episodes, and locations, but I will only be
using the characters and episodes. I will associate the characters
with what episodes they were in and I will also associate the
characterswith a favourite food with Faker::Science and Faker::Food.</p>

app/views/characters/index.html.erb
<h1>Characters</h1>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/characters">Characters</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/episodes">Episodes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
  </ul>

  <%= form_with(url: search_results_characters_path, method: "get", class:"form-inline", local: true) do %>
    <%= text_field_tag(:query, "", class:"form-control mr-sm-2",placeholder:"Search Characters") %>
    <%= submit_tag("Search", class:"btn btn-success") %>
  <% end %>
</nav>

<div class="container" style="margin:auto;">
  <% @characters.each do |character|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to character.name, character%></h4>
      <img class="card-img-top" src="<%= character.image %>" alt="Image is missing">
      <p class="card-text">status: <%= character.status %></p>
      <p class="card-text">species: <%= character.species %></p>
      <p class="card-text">origin: <%= character.origin %></p>
    </div>
  </div>
  <% end %>

<%==pagy_nav(@pagy)%>
</div>

app/views/characters/search_results.html.erb
<h1>Characters</h1>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/characters">Characters</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/episodes">Episodes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
  </ul>

  <%= form_with(url: search_results_characters_path, method: "get", class:"form-inline", local: true) do %>
    <%= text_field_tag(:query, "", class:"form-control mr-sm-2",placeholder:"Search Characters") %>
    <%= submit_tag("Search", class:"btn btn-success") %>
  <% end %>
</nav>

<p>
  Your search for '<%= @query %>' returned <%= pluralize(@characters.size, 'result') %>.
</p>

<div class="container" style="margin:auto;">
  <% @characters.each do |character|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to character.name, character%></h4>
      <img class="card-img-top" src="<%= character.image %>" alt="Image is missing">
      <p class="card-text">status: <%= character.status %></p>
      <p class="card-text">species: <%= character.species %></p>
      <p class="card-text">origin: <%= character.origin %></p>
    </div>
  </div>
  <% end %>

<%==pagy_nav(@pagy)%>
</div>

app/views/characters/show.html.erb
<h1>Characters</h1>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/characters">Characters</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/episodes">Episodes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
  </ul>

  <%= form_with(url: search_results_characters_path, method: "get", class:"form-inline", local: true) do %>
    <%= text_field_tag(:query, "", class:"form-control mr-sm-2",placeholder:"Search Characters") %>
    <%= submit_tag("Search", class:"btn btn-success") %>
  <% end %>
</nav>

<h2><%= @character.name %></h2>
<%= image_tag @character.image, alt: "Image not found"%>
<h3>status: <%= @character.status %></h3>
<h3>species: <%= @character.species %></h3>
<h3>origin: <%= @character.origin %></h3>

<h2>Favourite Food: </h2>
<h3>Name: <%= @character.favourite_food.name %></h3>
<h3>Description: <%= @character.favourite_food.description %></h3>

<h2>Episodes <%= @character.name %> appears in:</h2>

<% @character.episodes.each do |episode| %>
  <h3><%= link_to episode.name, episode %></h3>
<% end %>

app/views/episodes/index.html.erb
<h1>Episodes</h1>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/characters">Characters</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/episodes">Episodes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
  </ul>

  <%= form_with(url: search_results_characters_path, method: "get", class:"form-inline", local: true) do %>
    <%= text_field_tag(:query, "", class:"form-control mr-sm-2",placeholder:"Search Characters") %>
    <%= submit_tag("Search", class:"btn btn-success") %>
  <% end %>
</nav>

<div class="container" style="margin:auto;">
  <% @episodes.each do |episode|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to episode.name, episode%></h4>
      <p class="card-text">Air Date: <%= episode.air_date %></p>
      <p class="card-text">Episode: <%= episode.episode_name %></p>
    </div>
  </div>
  <% end %>

<%==pagy_nav(@pagy)%>
</div>

app/views/episodes/show.html.erb
<h1>Episodes</h1>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/characters">Characters</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/episodes">Episodes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
  </ul>

  <%= form_with(url: search_results_characters_path, method: "get", class:"form-inline", local: true) do %>
    <%= text_field_tag(:query, "", class:"form-control mr-sm-2",placeholder:"Search Characters") %>
    <%= submit_tag("Search", class:"btn btn-success") %>
  <% end %>
</nav>

<h2><%= @episode.name %></h2>
<h3>Air Date: <%= @episode.air_date %></h3>
<h3>Episode: <%= @episode.episode_name %></h3>

<h2>Characters that appear in the episode <%= @episode.name %></h2>

<% @episode.characters.each do |character| %>
  <h3><%= link_to character.name, character %></h3>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the Rick and Morty website!</h1>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/characters">Characters</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/episodes">Episodes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
  </ul>

  <%= form_with(url: search_results_characters_path, method: "get", class:"form-inline", local: true) do %>
    <%= text_field_tag(:query, "", class:"form-control mr-sm-2",placeholder:"Search Characters") %>
    <%= submit_tag("Search", class:"btn btn-success") %>
  <% end %>
</nav>

<p> This is a website that pulled all of the character and
episode data from a live API and turned it into a searchable
database, like a Rick and Morty library.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= yield %>
  </body>
</html>